AppSaresp_2024/Models/Aluno.cs
using System.ComponentModel.DataAnnotations;
using System.Numerics;

namespace AppSaresp_2024.Models
{
    public class Aluno
    {
        [Display(Name = "Código do Aluno")]
        public int IdAluno { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório!")]
        public string Nome { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "O email não é valido.")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email valido...")]
        public string Email { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "O campo Telefone é obrigatório!")]
        public BigInteger Telefone { get; set; }

        [Display(Name = "Serie")]
        [Required(ErrorMessage = "O campo serie é obrigatório!")]
        [StringLength(200, ErrorMessage = "Insira no máximo 200 digitos!")]
        public string Serie { get; set; }

        [Display(Name = "Turma")]
        [Required(ErrorMessage = "O campo turma é obrigatório!")]
        [StringLength(50, ErrorMessage = "Insira no máximo 50 digitos!")]
        public string Turma { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]
        public DateTime DataNasc { get; set; }
    }
}

AppSaresp_2024/Models/ErrorViewModel.cs
namespace AppSaresp_2024.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppSaresp_2024/Models/ProfessorAplicador.cs
using System.ComponentModel.DataAnnotations;
using System.Numerics;

namespace AppSaresp_2024.Models
{
    public class ProfessorAplicador
    {
        [Display(Name = "Código do Professor")]
        public int IdProfessor { get; set; }

        [Display(Name = "Nome Completo")]
        [Required(ErrorMessage = "O campo nome é obrigatório!")]
        public string Nome { get; set; }

        [Display(Name = "CPF")]
        [Required(ErrorMessage = "O campo CPF é obrigatório!")]
        //[MaxLength(11, ErrorMessage = "Insira apenas 11 digitos!")]
        public BigInteger CPF { get; set; }

        [Display(Name = "RG")]
        [Required(ErrorMessage = "O campo RG é obrigatório!")]
        //[MaxLength(9, ErrorMessage = "Insira apenas 9 digitos!")]
        public int RG { get; set; }

        [Display(Name = "Telefone")]
        [Required(ErrorMessage = "O campo Telefone é obrigatório!")]
        public BigInteger Telefone { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "O email não é valido.")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email valido...")]
        public string Email { get; set; }

        [Display(Name = "Nascimento")]
        [Required(ErrorMessage = "O campo nascimento é obrigatório")]
        [DataType(DataType.DateTime)]
        public DateTime DataNasc { get; set; }
    }
}

AppSaresp_2024/Controllers/AlunoController.cs
using AppSaresp_2024.Models;
using AppSaresp_2024.Repository.Contract;
using Microsoft.AspNetCore.Mvc;

namespace AppSaresp_2024.Controllers
{
    public class AlunoController : Controller
    {
        private IAlunoRepository _alunoRepository;
        public AlunoController(IAlunoRepository alunoRepository)
        {
            _alunoRepository = alunoRepository;
        }
        public IActionResult Index()
        {
            return View(_alunoRepository.ObterTodosAlunos());
        }
        [HttpGet]
        public IActionResult CadastrarAluno()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarAluno(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                _alunoRepository.Cadastrar(aluno);
            }
            return View();
        }
    }
}

AppSaresp_2024/Controllers/HomeController.cs
using AppSaresp_2024.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppSaresp_2024.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppSaresp_2024/Controllers/ProfessorAplicadorController.cs
using AppSaresp_2024.Models;
using AppSaresp_2024.Repository.Contract;
using Microsoft.AspNetCore.Mvc;
using MySqlX.XDevAPI;

namespace AppSaresp_2024.Controllers
{
    public class ProfessorAplicadorController : Controller
    {
        private IProfessorAplicadorRepository _professorAplicadorRepository;
        public ProfessorAplicadorController(IProfessorAplicadorRepository professorAplicadorRepository)
        {
            _professorAplicadorRepository = professorAplicadorRepository;
        }
        public IActionResult Index()
        {
            return View(_professorAplicadorRepository.ObterTodosProfessores());
        }
        [HttpGet]
        public IActionResult CadastrarProfessor()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CadastrarProfessor(ProfessorAplicador professor)
        {
            if (ModelState.IsValid)
            {
                _professorAplicadorRepository.Cadastrar(professor);
            }
            return View();
        }
    }
}

AppSaresp_2024/Views/Aluno/CadastrarAluno.cshtml
@model AppSaresp_2024.Models.Aluno

@{
    ViewData["Title"] = "Cadastrar Aluno";
}

<h1>Cadastrar Aluno</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarAluno">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Serie" class="control-label"></label>
                <input asp-for="Serie" class="form-control" />
                <span asp-validation-for="Serie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Turma" class="control-label"></label>
                <input asp-for="Turma" class="form-control" />
                <span asp-validation-for="Turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppSaresp_2024/Views/Aluno/Index.cshtml
@model IEnumerable<AppSaresp_2024.Models.Aluno>

@{
    ViewData["Title"] = "View de alunos";
}

<h1>View de alunos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdAluno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Serie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNasc)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdAluno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Serie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Turma)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNasc)
            </td>
        </tr>
}
    </tbody>
</table>

AppSaresp_2024/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppSaresp_2024/Views/ProfessorAplicador/CadastrarProfessor.cshtml
@model AppSaresp_2024.Models.ProfessorAplicador

@{
    ViewData["Title"] = "Cadastrar Professor";
}

<h1>Cadastrar Professor</h1>

<h4>Professor Aplicador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarProfessor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RG" class="control-label"></label>
                <input asp-for="RG" class="form-control" />
                <span asp-validation-for="RG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppSaresp_2024/Views/ProfessorAplicador/Index.cshtml
@model IEnumerable<AppSaresp_2024.Models.ProfessorAplicador>

@{
    ViewData["Title"] = "Cadastro de professores";
}

<h1>View de professores</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdProfessor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNasc)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdProfessor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RG)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNasc)
            </td>
        </tr>
}
    </tbody>
</table>

AppSaresp_2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppSaresp_2024</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppSaresp_2024.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppSaresp_2024</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="CadastrarAluno">Cadastrar Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProfessorAplicador" asp-action="CadastrarProfessor">Cadastrar Professor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProfessorAplicador" asp-action="Index">Professores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppSaresp_2024 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>